//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelfirstMobilyasite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koltuk
    {
        public int KoltukNo { get; set; }
        public string Model { get; set; }
        public string Kumas { get; set; }
        public string Renk { get; set; }
        public int Fiyat { get; set; }
    }
}
