//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelfirstMobilyasite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YemekOdası
    {
        public int YemekOdaNo { get; set; }
        public string Malzeme { get; set; }
        public int KisiSayisi { get; set; }
        public int Fiyat { get; set; }
    }
}
